/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmacos;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel pablo perez
 */
public class VentanaMostrar extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMostrar.class.getName());

    /**
     * Creates new form VentanaMostrar
     */
    public VentanaMostrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarMedicamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblDatos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDatos.setBackground(new java.awt.Color(255, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre Generico", "Nombre Comercial", "Forma ", "Concentracion", "Stock ", "Fecha de vencimiento", "Precio"
            }
        ));
        tblDatos.setViewportView(jTable1);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tblDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(btnActualizar)
                .addGap(35, 35, 35)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        // Obliga a la tabla a guardar el texto que se esté editando en ese instante
        if (jTable1.isEditing()) {
            jTable1.getCellEditor().stopCellEditing();
        }
        
        int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        try {
            Connection con = Conexion.Conect();
            String sql = "UPDATE farmacos SET Nombre_generico=?, Nombre_comercial=?, Stock=?, Precio=? WHERE idfarmacos=?";
            PreparedStatement ps = con.prepareStatement(sql);
            
            // Aquí jTable1.getValueAt(fila, columna) obtiene el texto editado directamente de la celda
            ps.setString(1, jTable1.getValueAt(fila, 1).toString());
            ps.setString(2, jTable1.getValueAt(fila, 2).toString());
            ps.setString(3, jTable1.getValueAt(fila, 5).toString());
            ps.setString(4, jTable1.getValueAt(fila, 7).toString());
            ps.setInt(5, Integer.parseInt(jTable1.getValueAt(fila, 0).toString()));
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Medicamento actualizado correctamente");
            cargarMedicamentos(); // Recargas la tabla para ver los cambios
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila de la tabla primero");
    }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar este medicamento?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            try {
                Connection con = Conexion.Conect();
                String sql = "DELETE FROM farmacos WHERE idfarmacos=?";
                PreparedStatement ps = con.prepareStatement(sql);
                
                // Obtiene el ID de la fila seleccionada (columna 0)
                ps.setInt(1, Integer.parseInt(jTable1.getValueAt(fila, 0).toString()));
                
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Medicamento eliminado correctamente");
                cargarMedicamentos(); // Recarga la tabla limpia
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila de la tabla primero");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaMostrar dialog = new VentanaMostrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void cargarMedicamentos() {
        
        // Definimos el modelo sobreescribiendo el método que controla la edición
        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // El ID (columna 0) no se puede editar, las demás sí (devuelve true)
                return column != 0; 
            }
        };
    
        modelo.addColumn("Id");
        modelo.addColumn("Nombre Generico");
        modelo.addColumn("Nombre Comercial");
        modelo.addColumn("Forma");
        modelo.addColumn("Concentracion");
        modelo.addColumn("Stock");
        modelo.addColumn("Fecha de vencimiento");
        modelo.addColumn("Precio");

        jTable1.setModel(modelo);
    
    // Consulta adaptada a los nombres exactos de tu imagen
    String sql = "SELECT idfarmacos, Nombre_generico, Nombre_comercial, Forma_farmaceutica, Concentracion, Stock, Fecha_vencimiento, Precio FROM farmacos"; 
    
    try {
        Connection con = Conexion.Conect(); 
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
        
        while (rs.next()) {
            Object[] fila = new Object[8]; 
            
            fila[0] = rs.getInt("idfarmacos"); // Cambiado a idfarmacos
            fila[1] = rs.getString("Nombre_generico");
            fila[2] = rs.getString("Nombre_comercial");
            fila[3] = rs.getString("Forma_farmaceutica"); // Cambiado a Forma_farmaceutica
            fila[4] = rs.getString("Concentracion");
            fila[5] = rs.getString("Stock"); // Obtenido como String porque en tu BD es VARCHAR
            fila[6] = rs.getString("Fecha_vencimiento");
            fila[7] = rs.getString("Precio"); // Obtenido como String porque en tu BD es VARCHAR
            
            modelo.addRow(fila);
        }
    } catch (SQLException e) {
        System.out.println("Error al cargar medicamentos: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblDatos;
    // End of variables declaration//GEN-END:variables
}

